version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 999999
      POSTGRES_DB: Attestation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
 #   image: julialob/lobanova:latest
    depends_on:
      db:
        condition: service_healthy

    environment:
      - DB_USER=postgres
      - DB_PASSWORD=999999
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=Attestation


volumes:
  postgres_data: